/* ============================================================
   firebase-config.js — Template (safe to commit, no real keys)
   ============================================================
   DO NOT put real keys here.
   The real firebase-config.js is gitignored and generated by:
     1. GitHub Actions (from GitHub Secrets) for production
     2. Locally: copy this file to firebase-config.js and fill in your keys
   ============================================================ */

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth }       from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore }  from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const firebaseConfig = {
  apiKey:            "FIREBASE_API_KEY_PLACEHOLDER",
  authDomain:        "FIREBASE_AUTH_DOMAIN_PLACEHOLDER",
  projectId:         "FIREBASE_PROJECT_ID_PLACEHOLDER",
  storageBucket:     "FIREBASE_STORAGE_BUCKET_PLACEHOLDER",
  messagingSenderId: "FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER",
  appId:             "FIREBASE_APP_ID_PLACEHOLDER",
  measurementId:     "FIREBASE_MEASUREMENT_ID_PLACEHOLDER"
};

const _app = initializeApp(firebaseConfig);

export const firebaseAuth = getAuth(_app);
export const firebaseDb   = getFirestore(_app);

window.FIREBASE_AUTH = firebaseAuth;
window.FIREBASE_DB   = firebaseDb;

console.log('[FinAI] Firebase initialized ✓');
